### ISSUE TITLE
workshops snap cannot be seeded

### ISSUE THREAD

**Issue by jhenstridge** [canonical/workshops#32]
I had trouble adding workshops as a pre-installed snap to an Ubuntu Core image: with it included, the system fails to complete the seeding process.

The cause seems to be this plug on the snap:

https://github.com/canonical/workshops/blob/7b13e00fd9d9c5323b747aa4cfa93740e61c08fa/snap/snapcraft.yaml#L15-L22

While all the prerequisite snaps were also included in the image, the lxd snap doesn't include a matching plug here. Upgrading lxd from the store doesn't change this, so it never installs workshops. As the system hasn't completed seeding, this causes a bunch of follow-on problems for the system.

**Comment by jpnurmi** [comment]
Thanks, the plug was removed by https://github.com/canonical/workshops/commit/235ea64057826b916c656f5c43effb86490d9cb3 and https://github.com/canonical/workshops/commit/de4efe8bb010969214e308708ef26226e355d397.

**Comment by tillkamppeter** [comment]
@mvo @jamesh This problem occurs in general if we have a Snap A which needs another Snap B be installed in order to work correctly.

In my case it is any Snap which has print functionality. Those Snaps plug the recently released [`cups` interface](https://forum.snapcraft.io/t/the-cups-interface/) and the `cups` interface's slot is provided by the CUPS Snap, so these Snaps require the CUPS Snap to be installed.

As snapd has no general support for dependencies between Snaps we use the workaround of the fake content interface, putting the following into the `snapcraft.yaml` of Snap A:
```
plugs: 
   foo-install-B: 
     default-provider: B 
     interface: content 
     content: foo 
     target: $SNAP_DATA/foo 
```
This works for Snaps in general which we install from the Snap Store or from a `*.snap` file. If Snap A is seeded it breaks the system installation as described in the initial posting, even if Snap B is also seeded.

What we need in snapd is general support for `default-provider:` in any plug, not only content interfaces, so that one could do:
```
plugs: 
   use-feature-of-B: 
     default-provider: B 
```
or in the `snapcraft.yaml` of an application which prints:
```
plugs: 
   cups: 
     default-provider: cups 
```
to install the CUPS Snap (`cups`), so that the application can plug the `cups` interface (or even better, as the `cups` interface needs the CUPS Snap anyway, define the dependency internally in snapd).
